### ISSUE TITLE
[FR] Cartesian Product iterator

### ISSUE THREAD

**Issue by mProjectsCode** [Smoren/itertools-ts#45]
It would be great to be able to iterate over the [cartesian product](https://en.wikipedia.org/wiki/Cartesian_product) of multiple lists.

**Comment by Smoren** [comment]
Hi @mProjectsCode,

Thank you for your suggestion! It was implemented in `v1.27.0` release.

### New features
* set
  * `cartesianProduct()`
  * `cartesianProductAsync()`
* Stream
  * `cartesianProductWith()`
* AsyncStream
  * `cartesianProductWith()`

### Examples

```typescript
import { set } from 'itertools-ts';

const numbers = [1, 2];
const letters = ['a', 'b'];
const chars = ['!', '?'];

for (const tuple of set.cartesianProduct(numbers, letters, chars)) {
  console.log(tuple);
}
/*
  [1, 'a', '!'],
  [1, 'a', '?'],
  [1, 'b', '!'],
  [1, 'b', '?'],
  [2, 'a', '!'],
  [2, 'a', '?'],
  [2, 'b', '!'],
  [2, 'b', '?'],
*/
```

```typescript
import { Stream } from "itertools-ts";

const numbers = [1, 2];

const result = Stream.of(input)
  .cartesianProductWith(['a', 'b'], ['!', '?'])
  .toArray();
/*
[
  [1, 'a', '!'],
  [1, 'a', '?'],
  [1, 'b', '!'],
  [1, 'b', '?'],
  [2, 'a', '!'],
  [2, 'a', '?'],
  [2, 'b', '!'],
  [2, 'b', '?'],
]
*/
```

**Comment by mProjectsCode** [comment]
thanks :)

**Comment by Smoren** [comment]
Hi @mProjectsCode!
FYI: new major release with fully refactored Stream and AsyncStream for using generic types and save the typing! https://github.com/Smoren/itertools-ts/releases/tag/v2.0.0
